version: "3.9"
services:
  web:
    build: .
    ports:
      - "8009:8009"
    environment:
       - REDIS_HOST=redis
       - REDIS_PORT=6379
    links:
       - "redis:redis"
  redis:
    image: "redis:alpine"